sonar.organization=miguelfb19
sonar.projectKey=tienda-de-maria
sonar.projectName=Tienda de Maria
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/assets/**, src/index.css, dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
